### ISSUE TITLE
Implement New DFA Table

### ISSUE THREAD

**Issue by BassedWarrior** [MESC2004/Syntax_Highlighter_ITC_Dream_Team#11]
Implement the new DFA table to include all the states required for the 
required tokens to be analized.

**Comment by MESC2004** [comment]
Am i on this or no @BassedWarrior ?

**Comment by BassedWarrior** [comment]
Osea es que iba a hacer que la tabla como tal fuera un dict o un objeto. Pa que tuviera mayor relación entre las filas y las columnas. Pq así namás, sin ver la documentación y el dibujo del autómata, es muy difícil entender la tabla.

**Comment by MESC2004** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAA pense que era el de la tabla en excel como de referencia, o de latex directamente, construirla fuera de codigo desde el DFA y ya luego implementarla, creo otro issue? O con este mismo lo vamos haciendo. Plan on doing so tmrrow desde el AF del @JoseGlezMtz.

**Comment by MESC2004** [comment]
pr #22
